---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: content/blog/es
  label: Nicarali en espagnol
  create: all
  match: "**/*"
  templates:
  - post_es
- type: directory
  path: content/blog/fr
  label: Actualités
  create: all
  match: "**/*"
  templates:
  - post_fr
upload_dir: content/assets
public_path: "/content/assets"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: public
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: gatsby develop -p 8080 -H 0.0.0.0
